name: aiops
dependencies:
  - python=3.8
  - pandas
  - numpy=1.18.5
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - lxml
  # Plotting
  - conda-forge::nbformat
  - plotly::plotly
  - conda-forge::pygraphviz
  - seaborn
  - jupyter
  - notebook
  - pip
  - pip:
    - dc-cli
    - fasttext
    - pyvis
    - beautifulsoup4
    - mlflow
    - tensorflow==2.2
    - cdt==0.6.0
    - networkx==2.8.7
